name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.0
  http: ^1.6.0
  cookie_jar: ^4.0.0
  dio_cookie_manager: ^3.0.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  file_selector: ^1.1.0
  image_picker: ^1.2.1
  url_launcher: ^6.3.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true



